blank_issues_enabled: false
version: 2.1
contact_links:
  - name: ðŸ’¬ LangChain Forum
    url: https://forum.langchain.com/
    about: General community discussions and support
  - name: ðŸ“š langchain-litellm Documentation
    url: https://docs.langchain.com/oss/python/integrations/providers/litellm
    about: View the official langchain-litellm documentation
  - name: ðŸ“š Documentation issue
    url: https://github.com/langchain-ai/docs/issues/new?template=01-langchain.yml
    about: Report an issue related to the LangChain documentation
